create extension if not exists "pgcrypto";

create table if not exists public.drivers (
  id uuid primary key default gen_random_uuid(),
  full_name text not null,
  email text unique,
  pin_code text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.trucks (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  registration text,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.roster_shifts (
  id uuid primary key default gen_random_uuid(),
  shift_date date not null,
  shift_type text not null check (shift_type in ('day','night')),
  driver_id uuid references public.drivers(id) on delete set null,
  truck_id uuid references public.trucks(id) on delete set null,
  customer_id uuid references public.customers(id) on delete set null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.dockets (
  id uuid primary key default gen_random_uuid(),
  docket_number bigint generated by default as identity,
  docket_date date not null default current_date,
  driver_id uuid references public.drivers(id) on delete set null,
  truck_id uuid references public.trucks(id) on delete set null,
  customer_id uuid references public.customers(id) on delete set null,
  job_description text not null default '',
  start_time time,
  finish_time time,
  travel_hours numeric(6,2),
  total_hours numeric(6,2),
  tonne_load text,
  created_at timestamptz not null default now()
);

create table if not exists public.time_entries (
  id uuid primary key default gen_random_uuid(),
  driver_id uuid not null references public.drivers(id) on delete cascade,
  clock_in_at timestamptz not null,
  clock_out_at timestamptz,
  duty_description text,
  created_at timestamptz not null default now()
);

create table if not exists public.chat_messages (
  id uuid primary key default gen_random_uuid(),
  user_display_name text not null,
  message_text text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.photo_uploads (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  storage_path text not null,
  linked_table text,
  linked_id uuid,
  uploaded_by text,
  created_at timestamptz not null default now()
);

insert into public.drivers (full_name, email, pin_code)
values
  ('Timothy Grech', 'admin@grechbulkhaulage.com.au', '1001'),
  ('Barry Kibblewhite', null, '1002'),
  ('Thomas Harvey', null, '1003'),
  ('Lyam Drummond', null, '1004'),
  ('Orkhan Combe', null, '1005'),
  ('John Gurdler', null, '1006')
on conflict do nothing;

insert into public.trucks (code)
values ('TGRECH'), ('TIMMYG'), ('XP17NK')
on conflict do nothing;

insert into public.customers (name)
values ('ANA Asphalts'), ('HVIS'), ('Downer'), ('Spray Seal'), ('Tefol'), ('Other')
on conflict do nothing;
